[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "pnpm run db:generate",
  "pnpm run build"
]

[start]
cmd = "pnpm run start:prod"
